'''
write a program thet accepts two numbers from user and prints theri:
addition
substraction
multiplication 
division
'''
print("Enter first Number :")
a = int(input())

print("Enter second Number:")
b=int(input())

Addition=a + b
print("Addition is : ",Addition)

Subtraction = a - b
print("Subtraction is :",Subtraction)

Multiplication = a * b
print("Multiplication is :",Multiplication)

Division = a /b;
print("Division is :",Division)

